const path = require("path");
const fs = require("fs");
const countNull = require("../utils/countNull");
const db = require("../database/connection");
const fileChanges = require("../utils/fileModification");
const XLSX = require('xlsx');
const axios = require('axios');
const districtFormatServices = {
  
    async SelectedCode(filename, attributes) {
        const districts = [
            "NICOBARS",
            "NORTH AND MIDDLE ANDAMAN",
            "SOUTH ANDAMAN",
            "ANANTAPUR",
            "CHITTOOR",
            "EAST GODAVARI",
            "GUNTUR",
            "KRISHNA",
            "KURNOOL",
            "PRAKASAM",
            "SRI POTTI SRIRAMULU NELLORE",
            "SRIKAKULAM",
            "VISAKHAPATNAM",
            "VIZIANAGARAM",
            "WEST GODAVARI",
            "Y.S.R.",
            "ANJAW",
            "CHANGLANG",
            "DIBANG VALLEY",
            "EAST KAMENG",
            "EAST SIANG",
            "KRA DAADI",
            "KURUNG KUMEY",
            "LOHIT",
            "LOWER DIBANG VALLEY",
            "LOWER SIANG",
            "LOWER SUBANSIRI",
            "NAMSAI",
            "PAPUM PARE",
            "SIANG",
            "TAWANG",
            "TIRAP",
            "UPPER SIANG",
            "UPPER SUBANSIRI",
            "WEST KAMENG",
            "WEST SIANG",
            "BAKSA",
            "BARPETA",
            "BISWANATH",
            "BONGAIGAON",
            "CACHAR",
            "CHARAIDEO",
            "CHIRANG",
            "DARRANG",
            "DHEMAJI",
            "DHUBRI",
            "DIBRUGARH",
            "DIMA HASAO",
            "GOALPARA",
            "GOLAGHAT",
            "HAILAKANDI",
            "HOJAI",
            "JORHAT",
            "KAMRUP",
            "KAMRUP METROPOLITAN",
            "KARBI ANGLONG",
            "KARIMGANJ",
            "KOKRAJHAR",
            "LAKHIMPUR",
            "MAJULI",
            "MORIGAON",
            "NAGAON",
            "NALBARI",
            "SIVASAGAR",
            "SONITPUR",
            "SOUTH SALAMARA-MANKACHAR",
            "TINSUKIA",
            "UDALGURI",
            "WEST KARBI ANGLONG",
            "ARARIA",
            "ARWAL",
            "AURANGABAD",
            "BANKA",
            "BEGUSARAI",
            "BHAGALPUR",
            "BHOJPUR",
            "BUXAR",
            "DARBHANGA",
            "GAYA",
            "GOPALGANJ",
            "JAMUI",
            "JEHANABAD",
            "KAIMUR (BHABUA)",
            "KATIHAR",
            "KHAGARIA",
            "KISHANGANJ",
            "LAKHISARAI",
            "MADHEPURA",
            "MADHUBANI",
            "MUNGER",
            "MUZAFFARPUR",
            "NALANDA",
            "NAWADA",
            "PASHCHIM CHAMPARAN",
            "PATNA",
            "PURBI CHAMPARAN",
            "PURNIA",
            "ROHTAS",
            "SAHARSA",
            "SAMASTIPUR",
            "SARAN",
            "SHEIKHPURA",
            "SHEOHAR",
            "SITAMARHI",
            "SIWAN",
            "SUPAUL",
            "VAISHALI",
            "CHANDIGARH",
            "BALOD",
            "BALODA BAZAR",
            "BALRAMPUR",
            "BASTAR",
            "BEMETARA",
            "BIJAPUR",
            "BILASPUR",
            "DAKSHIN BASTAR DANTEWADA",
            "DHAMTARI",
            "DURG",
            "GARIYABAND",
            "JANJGIR - CHAMPA",
            "JASHPUR",
            "KABEERDHAM",
            "KONDAGAON",
            "KORBA",
            "KORIYA",
            "MAHASAMUND",
            "MUNGELI",
            "NARAYANPUR",
            "RAIGARH",
            "RAIPUR",
            "RAJNANDGAON",
            "SUKMA",
            "SURAJPUR",
            "SURGUJA",
            "UTTAR BASTAR KANKER",
            "DADRA AND NAGAR HAVELI",
            "DAMAN",
            "DIU",
            "NORTH GOA",
            "SOUTH GOA",
            "AHMADABAD",
            "AMRELI",
            "ANAND",
            "ARVALLI",
            "BANAS KANTHA",
            "BHARUCH",
            "BHAVNAGAR",
            "BOTAD",
            "CHHOTA UDEPUR",
            "DEVBHOOMI DWARKA",
            "DOHAD",
            "GANDHINAGAR",
            "GIR SOMNATH",
            "JAMNAGAR",
            "JUNAGADH",
            "KACHCHH",
            "KHEDA",
            "MAHESANA",
            "MAHISAGAR",
            "MORBI",
            "NARMADA",
            "NAVSARI",
            "PANCH MAHALS",
            "PATAN",
            "PORBANDAR",
            "RAJKOT",
            "SABAR KANTHA",
            "SURAT",
            "SURENDRANAGAR",
            "TAPI",
            "THE DANGS",
            "VADODARA",
            "VALSAD",
            "AMBALA",
            "BHIWANI",
            "CHARKHI DADRI",
            "FARIDABAD",
            "FATEHABAD",
            "GURGAON",
            "HISAR",
            "JHAJJAR",
            "JIND",
            "KAITHAL",
            "KARNAL",
            "KURUKSHETRA",
            "MAHENDRAGARH",
            "MEWAT",
            "PALWAL",
            "PANCHKULA",
            "PANIPAT",
            "REWARI",
            "ROHTAK",
            "SIRSA",
            "SONIPAT",
            "YAMUNANAGAR",
            "BILASPUR",
            "CHAMBA",
            "HAMIRPUR",
            "KANGRA",
            "KINNAUR",
            "KULLU",
            "LAHUL SPITI",
            "MANDI",
            "SHIMLA",
            "SIRMAUR",
            "SOLAN",
            "UNA",
            "ANANTNAG",
            "BADGAM",
            "BANDIPORA",
            "BARAMULA",
            "DODA",
            "GANDERBAL",
            "JAMMU",
            "KARGIL",
            "KATHUA",
            "KISHTWAR",
            "KULGAM",
            "KUPWARA",
            "LEH(LADAKH)",
            "PULWAMA",
            "PUNCH",
            "RAJOURI",
            "RAMBAN",
            "REASI",
            "SAMBA",
            "SHUPIYAN",
            "SRINAGAR",
            "UDHAMPUR",
            "BOKARO",
            "CHATRA",
            "DEOGHAR",
            "DHANBAD",
            "DUMKA",
            "GARHWA",
            "GIRIDIH",
            "GODDA",
            "GUMLA",
            "HAZARIBAGH",
            "JAMTARA",
            "KHUNTI",
            "KODARMA",
            "LATEHAR",
            "LOHARDAGA",
            "PAKUR",
            "PALAMU",
            "PASHCHIMI SINGHBHUM",
            "PURBI SINGHBHUM",
            "RAMGARH",
            "RANCHI",
            "SAHIBGANJ",
            "SARAIKELA-KHARSAWAN",
            "SIMDEGA",
            "BAGALKOT",
            "BANGALORE",
            "BANGALORE RURAL",
            "BELGAUM",
            "BELLARY",
            "BIDAR",
            "BIJAPUR",
            "CHAMARAJANAGAR",
            "CHIKKABALLAPURA",
            "CHIKMAGALUR",
            "CHITRADURGA",
            "DAKSHINA KANNADA",
            "DAVANAGERE",
            "DHARWAD",
            "GADAG",
            "GULBARGA",
            "HASSAN",
            "HAVERI",
            "KODAGU",
            "KOLAR",
            "KOPPAL",
            "MANDYA",
            "MYSORE",
            "RAICHUR",
            "RAMANAGARA",
            "SHIMOGA",
            "TUMKUR",
            "UDUPI",
            "UTTARA KANNADA",
            "YADGIR",
            "ALAPPUZHA",
            "ERNAKULAM",
            "IDUKKI",
            "KANNUR",
            "KASARAGOD",
            "KOLLAM",
            "KOTTAYAM",
            "KOZHIKODE",
            "MALAPPURAM",
            "PALAKKAD",
            "PATHANAMTHITTA",
            "THIRUVANANTHAPURAM",
            "THRISSUR",
            "WAYANAD",
            "LAKSHADWEEP",
            "AGAR MALWA",
            "ALIRAJPUR",
            "ANUPPUR",
            "ASHOKNAGAR",
            "BALAGHAT",
            "BARWANI",
            "BETUL",
            "BHIND",
            "BHOPAL",
            "BURHANPUR",
            "CHHATARPUR",
            "CHHINDWARA",
            "DAMOH",
            "DATIA",
            "DEWAS",
            "DHAR",
            "DINDORI",
            "GUNA",
            "GWALIOR",
            "HARDA",
            "HOSHANGABAD",
            "INDORE",
            "JABALPUR",
            "JHABUA",
            "KATNI",
            "KHANDWA (EAST NIMAR)",
            "KHARGONE (WEST NIMAR)",
            "MANDLA",
            "MANDSAUR",
            "MORENA",
            "NARSIMHAPUR",
            "NEEMUCH",
            "PANNA",
            "RAISEN",
            "RAJGARH",
            "RATLAM",
            "REWA",
            "SAGAR",
            "SATNA",
            "SEHORE",
            "SEONI",
            "SHAHDOL",
            "SHAJPUR",
            "SHEOPUR",
            "SHIVPURI",
            "SIDHI",
            "SINGRAULI",
            "TIKAMGARH",
            "UJJAIN",
            "UMARIA",
            "VIDISHA",
            "AHMADNAGAR",
            "AKOLA",
            "AMRAVATI",
            "AURANGABAD",
            "BHANDARA",
            "BID",
            "BULDANA",
            "CHANDRAPUR",
            "DHULE",
            "GADCHIROLI",
            "GONDIYA",
            "HINGOLI",
            "JALGAON",
            "JALNA",
            "KOLHAPUR",
            "LATUR",
            "MUMBAI",
            "MUMBAI SUBURBAN",
            "NAGPUR",
            "NANDED",
            "NANDURBAR",
            "NASHIK",
            "OSMANABAD",
            "PALGHAR",
            "PARBHANI",
            "PUNE",
            "RAIGARH",
            "RATNAGIRI",
            "SANGLI",
            "SATARA",
            "SINDHUDURG",
            "SOLAPUR",
            "THANE",
            "WARDHA",
            "WASHIM",
            "YAVATMAL",
            "BISHNUPUR",
            "CHANDEL",
            "CHURACHANDPUR",
            "IMPHAL EAST",
            "IMPHAL WEST",
            "JIRIBAM",
            "KAKCHING",
            "KAMJONG",
            "KANGPOKPI",
            "NONEY",
            "PHERZAWL",
            "SENAPATI",
            "TAMENGLONG",
            "TENGNoupal",
            "THOUBAL",
            "UKHRUL",
            "EAST GARO HILLS",
            "EAST JAINTIA HILLS",
            "EAST KHASI HILLS",
            "JAINTIA HILLS",
            "NORTH GARO HILLS",
            "RIBHOI",
            "SOUTH GARO HILLS",
            "SOUTH WEST GARO HILLS",
            "SOUTH WEST KHASI HILLS",
            "WEST GARO HILLS",
            "WEST JAINTIA HILLS",
            "WEST KHASI HILLS",
            "AIZAWL",
            "CHAMPHAI",
            "KOLASIB",
            "LAWNGTLAI",
            "LUNGLEI",
            "MAMIT",
            "SAIHA",
            "SERCHHIP",
            "DIMAPUR",
            "KIPHIRE",
            "KOHIMA",
            "LONGLeng",
            "MOKOKCHUNG",
            "MON",
            "PEREN",
            "PHEK",
            "TUENsang",
            "WOKHA",
            "ZUNHEBOTO",
            "CENTRAL",
            "EAST",
            "NEW DELHI",
            "NORTH",
            "NORTH EAST",
            "NORTH WEST",
            "SHAHdara",
            "SOUTH",
            "SOUTH EAST DELHI",
            "SOUTH WEST",
            "WEST",
            "ANUGUL",
            "BALANGIR",
            "BALESHWAR",
            "BARGARH",
            "BAUDH",
            "BHADRAK",
            "CUTTACK",
            "DEBAGARH",
            "DHENKANAL",
            "GAJAPATI",
            "GANJAM",
            "JAGATSINGHAPUR",
            "JAJAPUR",
            "JHARSUGUDA",
            "KALAHANDI",
            "KANDHAMAL",
            "KENDRAPARA",
            "KENDUJHAR",
            "KHORDHA",
            "KORAPUT",
            "MALKANGIRI",
            "MAYURBHANJ",
            "NABARANGAPUR",
            "NAYAGARH",
            "NUAPADA",
            "PURI",
            "RAYAGADA",
            "SAMBALPUR",
            "SUBARNAPUR",
            "SUNDARGARH",
            "KARAIKAL",
            "MAHE",
            "PUDUCHERRY",
            "YANAM",
            "AMRITSAR",
            "BARNALA",
            "BATHINDA",
            "FARIDKOT",
            "FATEHGARH SAHIB",
            "FAZILKA",
            "FIROZPUR",
            "GURDASPUR",
            "HOSHIARPUR",
            "JALANDHAR",
            "KAPURTHALA",
            "LUDHIANA",
            "MANSA",
            "MOGA",
            "MUKTSAR",
            "PATHANKOT",
            "PATIALA",
            "RUPNAGAR",
            "SAHIBZADA AJIT SINGH NAGAR",
            "SANGRUR",
            "SHAHID BHAGAT SINGH NAGAR",
            "TARN TARAN",
            "AJMER",
            "ALWAR",
            "BANSWARA",
            "BARAN",
            "BARMER",
            "BHARATPUR",
            "BHILWARA",
            "BIKANER",
            "BUNDI",
            "CHITTAURGARH",
            "CHURU",
            "DAUSA",
            "DHAULPUR",
            "DUNGARPUR",
            "HANUMANGARH",
            "JAIPUR",
            "JAISALMER",
            "JALOR",
            "JHALAWAR",
            "JHUNJHUNUN",
            "JODHPUR",
            "KAULAUR",
            "KOTA",
            "NAGAUR",
            "PALI",
            "PRATAPGARH",
            "RAJSAMAND",
            "SAWAI MADHOPUR",
            "SIKAR",
            "SIROHI",
            "SRI GANGANAGAR",
            "TONK",
            "UDAIPUR",
            "EAST DISTRICT",
            "NORTH  DISTRICT",
            "SOUTH DISTRICT",
            "WEST DISTRICT",
            "ARIYALUR",
            "CHENNAI",
            "COIMBATORE",
            "CUDDALORE",
            "DHARMAPURI",
            "DINDIGUL",
            "ERODE",
            "KANCHEEPURAM",
            "KANNIYAKUMARI",
            "KARUR",
            "KRISHNAGIRI",
            "MADURAI",
            "NAGAPATTINAM",
            "NAMAKKAL",
            "PERAMBALUR",
            "PUDUKKOTTAI",
            "RAMANATHAPURAM",
            "SALEM",
            "SIVAGANGA",
            "THANJAVUR",
            "THE NILGIRIS",
            "THENI",
            "THIRUVALLUR",
            "THIRUVARUR",
            "THOOTHUKKUDI",
            "TIRUCHIRAPPALLI",
            "TIRUNELVELI",
            "TIRUPPUR",
            "TIRUVANNAMALAI",
            "VELLORE",
            "VILUPPURAM",
            "VIRUDHUNAGAR",
            "ADILABAD",
            "BHADRADRI KOTHAGUDEM",
            "HYDERABAD",
            "JAGTIAL",
            "JANGOAN",
            "JAYASHANKAR BHUPALAPALLI",
            "JOGLULAMBA GADWAL",
            "KAMAREDDY",
            "KARIMNAGAR",
            "KHAMMAM",
            "KUMURAM BHEEM ASIFABAD",
            "MAHBUBABAD",
            "MAHBUBNAGAR",
            "MANCHERIAL",
            "MEDAK",
            "MEDCHAL-MALKAJIGIRI",
            "NAGARKURNOOL",
            "NALGONDA",
            "NIRMAL",
            "NIZAMABAD",
            "PEDDAPALLI",
            "RAJANNA SIRCILLA",
            "RANGA REDDY",
            "SANGAREDDY",
            "SIDDIPET",
            "SURYAPET",
            "VIKARABAD",
            "WANAPARTHY",
            "WARANGAL (RURAL)",
            "WARANGAL (URBAN)",
            "YADADRI BHUVANAGIRI",
            "DHALAI",
            "GOMATI",
            "KHOWAI",
            "NORTH TRIPURA",
            "SEPAHIJALA",
            "SOUTH TRIPURA",
            "UNAKOTI",
            "WEST TRIPURA",
            "AGRA",
            "ALIGARH",
            "ALLAHABAD",
            "AMBEDKAR NAGAR",
            "AMETHI",
            "AMROHA",
            "AURAIYA",
            "AZAMGARH",
            "BAGHPAT",
            "BAHRAICH",
            "BALLIA",
            "BANDA",
            "BARABANKI",
            "BAREILLY",
            "BASTI",
            "BIJNOR",
            "BUDAUN",
            "BULANDSHAHR",
            "CHANDAULI",
            "CHITRAKOOT",
            "DEORIA",
            "ETAH",
            "ETAWAH",
            "FAIZABAD",
            "FARRUKHABAD",
            "FATEHPUR",
            "FIROZABAD",
            "GAUTAM BUDDHA NAGAR",
            "GHAZIABAD",
            "GHAZIPUR",
            "GONDA",
            "GORAKHPUR",
            "HAPUR",
            "HARDOI",
            "HATHRAS",
            "JALAUN",
            "JAUNPUR",
            "JHANSI",
            "KANNAUJ",
            "KANPUR DEHAT",
            "KANPUR NAGAR",
            "KASGANJ",
            "KAUSHAMBI",
            "KHERI",
            "KUSHI NAGAR",
            "LALITPUR",
            "LUCKNOW",
            "MAHARAJGANJ",
            "MAHOBA",
            "MAINPURI",
            "MATHURA",
            "MAU",
            "MEERUT",
            "MIRZAPUR",
            "MORADABAD",
            "MUZAFFARNAGAR",
            "PILIBHIT",
            "RAE BARELI",
            "RAMPUR",
            "SAHARANPUR",
            "SAMBHAL",
            "SANT KABIR NAGAR",
            "SHAHJAHANPUR",
            "SHAMLI",
            "SHRAVASTI",
            "SIDDHARTHNAGAR",
            "SITAPUR",
            "SONBHADRA",
            "SULTANPUR",
            "UNNAO",
            "VARANASI",
            "ALMORA",
            "BAGESHWAR",
            "CHAMOLI",
            "CHAMPAWAT",
            "DEHRADUN",
            "HARIDWAR",
            "NAINITAL",
            "PAURI GARHWAL",
            "PITHORAGARH",
            "RUDRA PRAYAG",
            "TEHRI GARHWAL",
            "UDAM SINGH NAGAR",
            "UTTARKASHI",
            "ALIPURDUAR",
            "BANKURA",
            "BIRBHUM",
            "COOCHBEHAR",
            "DARJEELING",
            "DINAJPUR DAKSHIN",
            "DINAJPUR UTTAR",
            "HOOGHLY",
            "HOWRAH",
            "JALPAIGURI",
            "JHARGRAM",
            "KALIMPONG",
            "KOLKATA",
            "MALDAH",
            "MEDINIPUR EAST",
            "MEDINIPUR WEST",
            "MURSHIDABAD",
            "NADIA",
            "PURULIA",
        ];
        
        try {
            // console.log(filename);
           

            console.log("hi:" +attributes);
            // console.log(attributes[0]);
            // console.log("-------")
            const filePath = path.join(__dirname, "..", "uploads", filename);
          
            const rawData = fs.readFileSync(filePath);
            const data = JSON.parse(rawData);
           
            const typ = attributes[0].value;
           
  
            console.log(data);
            console.log(typ);
          console.log("gi" +data[2][typ]);
          
         
        //       // Return the station codes as JSON
        // console.log("Hi"+stationCodes)
          
        // //   let originalDate;

        let I =0;
        let W =0;
        const combinedData = data.map(item => {
            const state = item[typ];
            
            var valid = "valid";

            if(districts.includes( item[typ].toUpperCase()) === true ){
                 valid  = "valid";
                 I++;
            }
            else{
                valid  = "Invalid";
                 W++;
            }
            // const vaild = stationCodes.includes(item[typ]) ? "Valid" : "NotValid";
            return { state, valid };
            // return stationCodes.includes(item[typ]);
        });
        
          const comb = {data : combinedData, errorcount : W,validCount :I}
        console.log(comb);
        
            return comb;
        } catch (err) {
            console.error("Error fetching logs:", err);
            throw new Error("Internal Server Error");
        }
    },
    async createLog(logData) {
      try {
        await db.query(
          "INSERT INTO stationcode (filename, error_percentage,created_time) VALUES ($1, $2,$3)",
          [logData.filename, logData.error_percentage,logData.created_time]
        );
        
      } catch (error) {
        console.error("Error creating log entry:", error);
        throw new Error("Internal Server Error");
      }
    },
    async getlogs() {
      try {
          const result = await db.query(
          "SELECT * FROM stationcode"
        );
        return result.rows;
        
      } catch (error) {
        console.error("Error creating log entry:", error);
        throw new Error("Internal Server Error");
      }
    },
    
    async viewFile(log) {
        console.log(log)
      try {
          const result = await db.query(
          "SELECT * FROM stationcode"
        );
        return result.rows;
        
      } catch (error) {
        console.error("Error creating log entry:", error);
        throw new Error("Internal Server Error");
      }
    }
  };
  module.exports = districtFormatServices;